### ISSUE TITLE
css_to_xpath error in rstudio docker image

### ISSUE THREAD

**Issue by qinwf** [sjp/selectr#7]
Hi, when I use `rvest` and it will report,

```
Error in do.call(method, list(parsed_selector)) : 
  could not find function "xpath_combinedselector"
```

then I find out it come from this:

```
> selectr::css_to_xpath(".download-links a")
Error in do.call(method, list(parsed_selector)) : 
  could not find function "xpath_combinedselector"
```

Maybe I need to install some debian xml packages on this docker containers? I already try install `libxml2-dev`, and still have this error.

This docker container is from:

```
docker pull rocker/rstudio
```

Thanks!

**Comment by qinwf** [comment]
To be more specific, I use this image https://github.com/rocker-org/hadleyverse

**Comment by sjp** [comment]
Thanks -- this should not be related to the use of the `XML` or `xml2` packages. This is because it's just doing translation at this point and not querying any documents.

The error message is suggesting to me that there is something not working properly when interacting with the `methods` package. This is because `selectr` depends on `usingMethods()` in reference classes which for some reason isn't picking up the `xpath_combinedselector` method (see: https://stat.ethz.ch/R-manual/R-devel/library/methods/html/refClass.html).

It might take me some time to track this down because I don't have an environment to test out any Docker images at the moment.

**Comment by stefanfritsch** [comment]
For what it's worth, I had the same issue and it disappears if I install the current github version (actually the github versions of both rvest and selectr but I'm not sure if it was necessary vor rvest). Reinstalling selectr from CRAN didn't fix it.

So maybe you've already squashed that bug.

**Comment by qinwf** [comment]
Thanks @stefanfritsch , it works. I just installed the GitHub version.

**Comment by sjp** [comment]
Thanks for tracking down a workaround. I'm not entirely convinced that the bug lies in `selectr` yet. However, there is nothing I'm waiting on to push a new version to CRAN so I'll do that within the next few days.

If pushing a new version does not fix the problem then I guess the problem exists somewhere in the docker image.

**Comment by sjp** [comment]
I've pushed a new release to CRAN. Does the latest release fix your problem?

**Comment by qinwf** [comment]
Yes, I think we can close this now.

**Comment by pgensler** [comment]
I think this is still an issue, the example from rvest::html_nodes:
https://github.com/hadley/rvest/blob/master/R/selectors.R

```
> link <- c("http://www.boxofficemojo.com/movies/?id=ateam.htm")
> ##error on counld not find function xpath_element
> contents_1 <- link %>% 
+   xml2::read_html() %>%
+   rvest::html_nodes(css = "pre") %>%
+   rvest::html_text()
Error in xpath_element(<S4 object of class "Element">) : 
  could not find function "xpath_element"
> 
> #this gives me contents_2 with nothing inside it
> contents_2 <- link %>%
+   xml2::read_html() %>%
+   rvest::html_nodes(xpath = "//pre") %>%
+   rvest::html_text()

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] selectr_0.3-1   XML_3.98-1.9    RCurl_1.95-4.8  bitops_1.0-6   
 [5] magrittr_1.5    rvest_0.3.2     xml2_1.1.1      dplyr_0.7.4    
 [9] purrr_0.2.4     readr_1.1.1     tidyr_0.7.2     tibble_1.3.4   
[13] ggplot2_2.2.1   tidyverse_1.1.1 pacman_0.4.6   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     cellranger_1.1.0 compiler_3.4.2   plyr_1.8.4      
 [5] bindr_0.1        forcats_0.2.0    tools_3.4.2      lubridate_1.7.0 
 [9] jsonlite_1.5     nlme_3.1-131     gtable_0.2.0     lattice_0.20-35 
[13] pkgconfig_2.0.1  rlang_0.1.2      psych_1.7.8      curl_3.0        
[17] yaml_2.1.14      parallel_3.4.2   haven_1.1.0      bindrcpp_0.2    
[21] httr_1.3.1       stringr_1.2.0    hms_0.3          grid_3.4.2      
[25] glue_1.2.0.9000  R6_2.2.2         readxl_1.0.0     foreign_0.8-69  
[29] modelr_0.1.1     reshape2_1.4.2   scales_0.5.0     assertthat_0.2.0
[33] mnormt_1.5-5     colorspace_1.3-2 stringi_1.1.5    lazyeval_0.2.1  
[37] munsell_0.4.3    broom_0.4.2    
```

Related:

https://github.com/ropensci/rrricanes/issues/67
https://stackoverflow.com/questions/40874011/r-rvest-could-not-find-function-xpath-element

**Comment by pgensler** [comment]
Just to clarify, with my example on a Debian docker container:


```
> #this returns cannot find function xpath_combinedselector
> data2 <- "https://www.ratebeer.com/top/wheat-ale" %>%
+   read_html() %>%
+   html_nodes(css = ".table a")
Error in xpath_combinedselector(<S4 object of class "CombinedSelector">) : 
  could not find function "xpath_combinedselector"
> 
> data3 <- "https://www.ratebeer.com/top/wheat-ale" %>%
+   read_html() %>%
+   html_nodes(xpath = '//a')
> str(data3)
List of 44
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 - attr(*, "class")= chr "xml_nodeset"
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] selectr_0.3-1   XML_3.98-1.9    RCurl_1.95-4.8  bitops_1.0-6   
 [5] magrittr_1.5    rvest_0.3.2     xml2_1.1.1      dplyr_0.7.4    
 [9] purrr_0.2.4     readr_1.1.1     tidyr_0.7.2     tibble_1.3.4   
[13] ggplot2_2.2.1   tidyverse_1.1.1 pacman_0.4.6   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     cellranger_1.1.0 compiler_3.4.2   plyr_1.8.4      
 [5] bindr_0.1        forcats_0.2.0    tools_3.4.2      lubridate_1.7.0 
 [9] jsonlite_1.5     nlme_3.1-131     gtable_0.2.0     lattice_0.20-35 
[13] pkgconfig_2.0.1  rlang_0.1.2      psych_1.7.8      curl_3.0        
[17] yaml_2.1.14      parallel_3.4.2   haven_1.1.0      bindrcpp_0.2    
[21] httr_1.3.1       stringr_1.2.0    hms_0.3          grid_3.4.2      
[25] glue_1.2.0.9000  R6_2.2.2         readxl_1.0.0     foreign_0.8-69  
[29] modelr_0.1.1     reshape2_1.4.2   scales_0.5.0     assertthat_0.2.0
[33] mnormt_1.5-5     colorspace_1.3-2 stringi_1.1.5    lazyeval_0.2.1  
[37] munsell_0.4.3    broom_0.4.2 
```

**Comment by sjp** [comment]
Thanks for the update.

I'll try to investigate this further seeing as we clearly haven't resolved the problem.

Can you please provide steps to reproduce this?

**Comment by pgensler** [comment]
@sjp  the easiest way would be to download docker for mac, pull my container, 
run it with the steps on docker hub from here:
https://hub.docker.com/r/pgensler/sandboxr/

`docker run -d -p 8787:8787 -v ~/Desktop:/home/rstudio pgensler/sandboxr`
the login and password are rstudio

and run the script provided above. Does that make sense?

**Comment by sjp** [comment]
Sure. That's fine, I can reproduce from those instructions. Thanks.

**Comment by clement-parisot** [comment]
I confirm, I have the same issue here (Centos7). I give you the output of the example in `rvest` documentation and output of `sessionInfo()` right after.
```
> library(rvest)
Loading required package: xml2
> lego_movie <- read_html("http://www.imdb.com/title/tt1490017/")
> 
> rating <- lego_movie %>% 
+   html_nodes("strong span") %>%
+   html_text() %>%
+   as.numeric()
Error in xpath_combinedselector(<S4 object of class "CombinedSelector">) : 
  could not find function "xpath_combinedselector"
> rating
Error: object 'rating' not found
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /mnt/irisgpfs/apps/resif/data/production/v0.1-20170602/default/software/lang/R/3.4.0-intel-2017a-X11-20170314-bare/lib64/R/lib/libR.so
LAPACK: /mnt/irisgpfs/apps/resif/data/production/v0.1-20170602/default/software/lang/R/3.4.0-intel-2017a-X11-20170314-bare/lib64/R/modules/lapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rvest_0.3.2 xml2_1.1.1 

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.0 selectr_0.3-1  magrittr_1.5   R6_2.2.2      
 [6] tools_3.4.0    curl_3.0       Rcpp_0.12.13   stringi_1.1.5  stringr_1.2.0 
```

**Comment by sjp** [comment]
Hi,

A bit of a delayed update, but I've attempted to reproduce this issue again and am unable to do so. I'm getting no errors and the output is as expected.

Is anyone able to reproduce this now with any of the commonly available docker images?

**Comment by pgensler** [comment]
I think this is still an issue, try using this RStudio.Cloud project, and see if this helps to resolve it:
https://rstudio.cloud/project/21779
```r
> library(rvest)
> library(magrittr)
> library(xml2)
> library(devtools)
> #this returns cannot find function xpath_combinedselector
> data2 <- "https://www.ratebeer.com/top/wheat-ale" %>%
+     read_html() %>%
+     html_nodes(css = ".table a")
Error in xpath_combinedselector(<S4 object of class "CombinedSelector">) : 
  could not find function "xpath_combinedselector"
> Error in xpath_combinedselector(<S4 object of class "CombinedSelector">) : 
Error: unexpected 'in' in "Error in"
>   could not find function "xpath_combinedselector"
Error: unexpected symbol in "  could not"
>  
> data3 <- "https://www.ratebeer.com/top/wheat-ale" %>%
+      read_html() %>%
+      html_nodes(xpath = '//a')
>  str(data3)
List of 44
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 - attr(*, "class")= chr "xml_nodeset"
> session_info()
Session info ---------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, linux-gnu           
 ui       RStudio (1.2.327.1)         
 language (EN)                        
 collate  C.UTF-8                     
 tz       Zulu                        
 date     2018-03-03                  

Packages -------------------------------------------------------------------------------------------------------------------------
 package    * version date       source        
 base       * 3.4.3   2017-11-30 local         
 compiler     3.4.3   2017-11-30 local         
 curl         3.1     2017-12-12 CRAN (R 3.4.3)
 datasets   * 3.4.3   2017-11-30 local         
 devtools   * 1.13.5  2018-02-18 local         
 digest       0.6.15  2018-01-28 CRAN (R 3.4.3)
 graphics   * 3.4.3   2017-11-30 local         
 grDevices  * 3.4.3   2017-11-30 local         
 httr         1.3.1   2017-08-20 CRAN (R 3.4.3)
 magrittr   * 1.5     2014-11-22 CRAN (R 3.4.3)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.3)
 methods    * 3.4.3   2017-11-30 local         
 R6           2.2.2   2017-06-17 CRAN (R 3.4.3)
 Rcpp         0.12.15 2018-01-20 CRAN (R 3.4.3)
 rstudioapi   0.7     2017-09-07 CRAN (R 3.4.3)
 rvest      * 0.3.2   2016-06-17 CRAN (R 3.4.3)
 selectr      0.3-1   2016-12-19 CRAN (R 3.4.3)
 stats      * 3.4.3   2017-11-30 local         
 stringi      1.1.6   2017-11-17 CRAN (R 3.4.3)
 stringr      1.3.0   2018-02-19 CRAN (R 3.4.3)
 tools        3.4.3   2017-11-30 local         
 utils      * 3.4.3   2017-11-30 local         
 withr        2.1.1   2017-12-19 CRAN (R 3.4.3)
 xml2       * 1.2.0   2018-01-24 CRAN (R 3.4.3)
```

**Comment by sjp** [comment]
Thanks!

I was able to reproduce well with that rstudio cloud link. I've made some changes to fix this.

Does the following code work for you?

```r
library(xml2)
library(devtools)
install_github("sjp/selectr")

library(rvest)
library(magrittr)
#this returns cannot find function xpath_combinedselector
data2 <- "https://www.ratebeer.com/top/wheat-ale" %>%
    read_html() %>%
    html_nodes(css = "div")
```

**Comment by pgensler** [comment]
This works much better, I think this may have been fixed:

``` r
> data2 <- "https://www.ratebeer.com/top/wheat-ale" %>%
+   read_html() %>%
+   html_nodes(css = "div")
> str(data2)
List of 50
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 $ :List of 2
  ..$ node:<externalptr> 
  ..$ doc :<externalptr> 
  ..- attr(*, "class")= chr "xml_node"
 - attr(*, "class")= chr "xml_nodeset"
```

**Comment by sjp** [comment]
Great! Thanks for double-checking that.

The cause of the bug appears to be due to the way in which reference classes work. They delay binding of methods until they are called via the `$` operator. Because we're not invoking the methods in that way it appears to (sometimes) be causing the missing method error.

I haven't worked out why this is only sometimes occurring. However, the solution should work regardless.

I'll try to push a new version of the package sometime this week to address this issue.

**Comment by sjp** [comment]
I'm closing this now as I believe this is fixed as of c0bb44a. If this issue persists, feel free to re-open it.

The CRAN release will be pushed out later this week.
